/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import java.util.ArrayList;
import Control.produtoControl;
import Objects.produto;
import Objects.produtosVenda;
import Objects.vendas;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Beth
 */
public class buscarProduto extends javax.swing.JFrame {

    ArrayList lista; 
    vendas dadosDavenda= new vendas(); 
    /**
     * Creates new form buscarProduto
     */
    public buscarProduto() {
        initComponents();
    }
    
    public void armazenarDados(vendas venda){
        dadosDavenda=venda;
    }
    
    public void arrumaTabela(String pesquisar){
        produtoControl acessar= new produtoControl();
        lista= acessar.validarNomePesquisa(pesquisar);
        if(lista!=null){
            DefaultTableModel modelo= (DefaultTableModel) Tab_produtos.getModel();
            while(modelo.getRowCount()!=0){
                modelo.removeRow(0);
            }
            for(int i=0;i<lista.size();i++){
                produto prod = new produto(); 
                prod=(produto) lista.get(i);
                String[] linha=new String[4];
                linha[0]=prod.getNome();
                linha[1]="R$ "+String.valueOf(prod.getValorUnitario());
                modelo.addRow(linha);
                Tab_produtos.setModel(modelo);
            }
        }else{
            System.out.println("\nArrayList retornou nulo");
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        Tab_produtos = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Produtos Localizados");

        Tab_produtos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Produto", "Valor Unitário"
            }
        ));
        Tab_produtos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Tab_produtosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Tab_produtos);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Produtos Encontrados:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 403, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel1)
                .addGap(38, 38, 38)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void Tab_produtosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Tab_produtosMouseClicked
        int posicao=Tab_produtos.getSelectedRow();
        produto prod= (produto) lista.get(posicao);
        produtosVenda prodVenda= new produtosVenda();
        prodVenda.setCodigoProduto(prod.getCodigo());
        prodVenda.setCodigoVenda(dadosDavenda.getCodigo());
        prodVenda.setValorUnitario(prod.getValorUnitario());
        prodVenda.setNome(prod.getNome());
        prodVenda.setQuantidade(1);
        prodVenda.setTotalProduto(prod.getValorUnitario());
        dadosDavenda.addItem(prodVenda);
        System.out.println("\nQtd da Lista em buscar produto "+dadosDavenda.retornarItens().size());
        vendaPresencial vp= new vendaPresencial();
        vp.arrumaTela(dadosDavenda);
        vp.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Tab_produtosMouseClicked


    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(buscarProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(buscarProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(buscarProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(buscarProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new buscarProduto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Tab_produtos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
