/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import Control.vendaControl;
import Objects.vendas;
import java.text.ParseException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFormattedTextField;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.MaskFormatter;

/**
 *
 * @author natty
 */
public class listarVendaPresencial extends javax.swing.JFrame {

    vendaControl vendasControl = new vendaControl();
    private String user;
    
    public void setUser(String user) {
        this.user = user;
    }
    
    /**
     * Creates new form listarVendaPresencial
     */
    public listarVendaPresencial() {
        initComponents();
        arrumarTela();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        B_pesquisar = new javax.swing.JButton();
        B_novo = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tab_vendas = new javax.swing.JTable();
        CT_data = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jLabel1.setText("Filtrar por data:");

        B_pesquisar.setText("Pesquisar");
        B_pesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_pesquisarActionPerformed(evt);
            }
        });

        B_novo.setText("Novo");
        B_novo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_novoActionPerformed(evt);
            }
        });

        Tab_vendas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Código", "Data", "Valor Total"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Tab_vendas.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                Tab_vendasFocusGained(evt);
            }
        });
        Tab_vendas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Tab_vendasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Tab_vendas);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CT_data, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(B_pesquisar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(B_novo)))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(B_pesquisar)
                    .addComponent(B_novo)
                    .addComponent(CT_data, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void B_pesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_pesquisarActionPerformed
        arrumaTabela();
    }//GEN-LAST:event_B_pesquisarActionPerformed

    private void B_novoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_novoActionPerformed
        this.setVisible(false);
        new vendaPresencial(this, rootPaneCheckingEnabled).show();
        this.setVisible(true);
        CT_data.setText("");
        arrumaTabela();
    }//GEN-LAST:event_B_novoActionPerformed

    private void Tab_vendasFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Tab_vendasFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_Tab_vendasFocusGained

    private void Tab_vendasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Tab_vendasMouseClicked
        int linha = Tab_vendas.getSelectedRow();
        vendas venda = new vendas();
        venda.setCodigo(Integer.parseInt(Tab_vendas.getValueAt(linha, 0).toString()));
        venda.setDataVenda(Tab_vendas.getValueAt(linha, 1).toString());
        venda.setTotal(Float.parseFloat(Tab_vendas.getValueAt(linha, 2).toString()));
        this.setVisible(false);
        vendaPresencial vendaP = new vendaPresencial(this, rootPaneCheckingEnabled);
        vendaP.arrumaTela(venda);
        vendaP.setVisible(true);
        CT_data.setText("");
        arrumaTabela();
        this.setVisible(true);
    }//GEN-LAST:event_Tab_vendasMouseClicked

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        telaInicial ini= new telaInicial();
        ini.arrumaTela(user);
        ini.setVisible(true);
    }//GEN-LAST:event_formWindowClosing

    public void arrumaTabela() {
        ArrayList resultado = vendasControl.validarDataPesquisa(CT_data.getText());
        if (resultado != null) {
            DefaultTableModel modelo = (DefaultTableModel) Tab_vendas.getModel();
            while (modelo.getRowCount() != 0) {
                modelo.removeRow(0);
            }
            for (int i = 0; i < resultado.size(); i++) {
                vendas vendasv = new vendas();
                vendasv = (vendas) resultado.get(i);
                String[] linha = new String[3];
                linha[0] = String.valueOf(vendasv.getCodigo());
                linha[1] = vendasv.getDataVenda();
                linha[2] = String.valueOf(vendasv.getTotal());
                modelo.addRow(linha);
                Tab_vendas.setModel(modelo);
            }
        } else {
            System.out.println("\nNão há vendas cadastradas");
        }
    }

    public void arrumarTela() {
        CT_data.setText("");
        CT_data.requestFocus();
        //aplicarMascara();
        arrumaTabela();
    }
    
    public void aplicarMascara() {
        try {
            MaskFormatter mascara = new MaskFormatter("##/##/####");
            mascara.install(CT_data);
        } catch (ParseException ex) {
            Logger.getLogger(vendaPresencialteste.class.getName()).log(Level.SEVERE, null, ex);
        }
        arrumaTabela();
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(listarVendaPresencial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(listarVendaPresencial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(listarVendaPresencial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(listarVendaPresencial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new listarVendaPresencial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton B_novo;
    private javax.swing.JButton B_pesquisar;
    private javax.swing.JFormattedTextField CT_data;
    private javax.swing.JTable Tab_vendas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
