/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import Control.produtoVendaControl;
import java.util.Date;
import Control.vendaControl;
import Objects.vendas;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author felip
 */
public class visualizarVenda extends javax.swing.JFrame {

    vendaControl controle = new vendaControl();
    vendas vend = new vendas();
    ArrayList listaVendas = new ArrayList();
    private boolean fechar = false;
    private String user;

    public void setUser(String user) {
        this.user = user;
    }

    /**
     * Creates new form visualizarVenda
     */
    public visualizarVenda() {
        initComponents();
        iniciar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        CAL_dataInicial = new com.toedter.calendar.JDateChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tab_vendas = new javax.swing.JTable();
        B_filtrar = new javax.swing.JButton();
        B_listarTudo = new javax.swing.JButton();
        CAL_datafinal = new com.toedter.calendar.JDateChooser();
        jLabel2 = new javax.swing.JLabel();
        B_novo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Listar Vendas");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("De:");

        Tab_vendas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Venda do dia", "Total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Tab_vendas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Tab_vendasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Tab_vendas);

        B_filtrar.setText("Filtrar");
        B_filtrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_filtrarActionPerformed(evt);
            }
        });

        B_listarTudo.setText("Limpar");
        B_listarTudo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_listarTudoActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Até:");

        B_novo.setText("Novo");
        B_novo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_novoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 467, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(CAL_datafinal, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(21, 21, 21)
                                .addComponent(CAL_dataInicial, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(B_filtrar)
                        .addGap(28, 28, 28)
                        .addComponent(B_listarTudo)
                        .addGap(30, 30, 30)
                        .addComponent(B_novo)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(B_filtrar)
                            .addComponent(B_listarTudo)
                            .addComponent(B_novo))
                        .addGap(1, 1, 1)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(CAL_dataInicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                        .addComponent(CAL_datafinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(29, 29, 29)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void B_filtrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_filtrarActionPerformed
        Date dataInicial = CAL_dataInicial.getDate();
        Date dataFinal = CAL_datafinal.getDate();
        listaVendas = controle.formatarData(dataInicial, dataFinal);
        if (listaVendas != null) {
            arrumarTabela();
        }
    }//GEN-LAST:event_B_filtrarActionPerformed

    private void B_listarTudoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_listarTudoActionPerformed
        iniciar();
    }//GEN-LAST:event_B_listarTudoActionPerformed

    private void Tab_vendasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Tab_vendasMouseClicked
        int res = Tab_vendas.getSelectedRow();
        vend = (vendas) listaVendas.get(res);
        vend.setDataVenda(Tab_vendas.getValueAt(res, 0).toString());
        produtosVenda(vend.getCodigo());
        vendaPresencial vp = new vendaPresencial();
        vp.arrumaTelaUpdate(vend);
        this.setVisible(false);
        vp.setUsuario(user);
        vp.setVisible(true);
        fechar=true;
        this.dispose();
    }//GEN-LAST:event_Tab_vendasMouseClicked

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        if (!fechar) {
            telaInicial start = new telaInicial();
            this.dispose();
            start.arrumaTela(user);
            start.setVisible(true);
        }
    }//GEN-LAST:event_formWindowClosed

    private void B_novoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_novoActionPerformed
        vendaPresencial vp= new vendaPresencial();
        vp.setUsuario(user);
        vp.setVisible(true);
        fechar=true;
        this.dispose();
    }//GEN-LAST:event_B_novoActionPerformed

    public void iniciar() {
        CAL_dataInicial.setDate(null);
        CAL_datafinal.setDate(null);
        listaVendas = controle.devolverTudo();
        arrumarTabela();
    }

    public void arrumarTabela() {
        DefaultTableModel modelo = (DefaultTableModel) Tab_vendas.getModel();
        while (modelo.getRowCount() != 0) {
            modelo.removeRow(0);
        }
        for (int i = 0; i < listaVendas.size(); i++) {
            String[] linha = new String[4];
            vendas venda = (vendas) listaVendas.get(i);
            linha[0] = formataData(venda.getDataVenda());
            linha[1] = "R$ " + venda.getTotal();
            modelo.addRow(linha);
        }
        Tab_vendas.setModel(modelo);
    }

    public String formataData(String data) {
        String dataFormatada = data.substring(8, 10) + "/" + data.substring(5, 7) + "/" + data.substring(0, 4);
        return dataFormatada;
    }

    //Localiza todos os itens da venda e os introduz nelas
    public void produtosVenda(int codigo) {
        produtoVendaControl prodVendaControl = new produtoVendaControl();
        vend.adicionarItens(prodVendaControl.itensVenda(codigo));
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(visualizarVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(visualizarVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(visualizarVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(visualizarVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new visualizarVenda().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton B_filtrar;
    private javax.swing.JButton B_listarTudo;
    private javax.swing.JButton B_novo;
    private com.toedter.calendar.JDateChooser CAL_dataInicial;
    private com.toedter.calendar.JDateChooser CAL_datafinal;
    private javax.swing.JTable Tab_vendas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
