/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import Control.clienteControl;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author felip
 */
public class visualizarClientes extends javax.swing.JDialog {

    clienteControl clientControl = new clienteControl();

    /**
     * Creates new form visualizarClientes
     */
    public visualizarClientes(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        arrumarTela();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        Tab_clientes = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        CT_nome = new javax.swing.JTextField();
        B_novo = new javax.swing.JButton();
        B_pesquisa = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        Tab_clientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Id", "Nome", "Endereço", "Telefone"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        Tab_clientes.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(Tab_clientes);

        jLabel1.setText("Filtrar por nome:");

        CT_nome.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                CT_nomeInputMethodTextChanged(evt);
            }
        });
        CT_nome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CT_nomeActionPerformed(evt);
            }
        });

        B_novo.setText("Novo");
        B_novo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_novoActionPerformed(evt);
            }
        });

        B_pesquisa.setText("Pesquisar");
        B_pesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_pesquisaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(CT_nome, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(B_pesquisa)
                        .addGap(18, 18, 18)
                        .addComponent(B_novo))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(CT_nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(B_novo)
                    .addComponent(B_pesquisa))
                .addGap(27, 27, 27)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void B_novoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_novoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B_novoActionPerformed

    private void CT_nomeInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_CT_nomeInputMethodTextChanged

    }//GEN-LAST:event_CT_nomeInputMethodTextChanged

    private void CT_nomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CT_nomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CT_nomeActionPerformed

    private void B_pesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_pesquisaActionPerformed
        arrumaTabela();
    }//GEN-LAST:event_B_pesquisaActionPerformed

    public void arrumaTabela() {
        ResultSet resultado = clientControl.validarNomePesquisa(CT_nome.getText());
        if (resultado != null) {
            DefaultTableModel modelo = (DefaultTableModel) Tab_clientes.getModel();
            while (modelo.getRowCount() != 0) {
                modelo.removeRow(0);
            }
            try {
                while (resultado.next()) {
                    String[] linha = new String[4];
                    linha[0] = String.valueOf(resultado.getInt("idcliente"));
                    linha[1] = resultado.getString("nome");
                    linha[2] = String.valueOf(resultado.getInt("telefone"));
                    linha[3] = resultado.getString("endereco");
                    modelo.addRow(linha);
                    Tab_clientes.setModel(modelo);
                }
                resultado.close();
            } catch (SQLException ex) {
                Logger.getLogger(visualizarClientes.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        else
            System.out.println("ResultSet retornou nulo");
    }
    
    public void arrumarTela(){
        CT_nome.setText("");
        arrumaTabela();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(visualizarClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(visualizarClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(visualizarClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(visualizarClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                visualizarClientes dialog = new visualizarClientes(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton B_novo;
    private javax.swing.JButton B_pesquisa;
    private javax.swing.JTextField CT_nome;
    private javax.swing.JTable Tab_clientes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
