/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import Control.encomendaControl;
import Control.produtoEncomendaControl;
import Objects.encomenda;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author felip
 */
public class visualizarEncomendas extends javax.swing.JFrame {

    ArrayList listaEncomendas = new ArrayList();
    encomenda  pedido = new encomenda();
    private boolean fechar;

    /**
     * Creates new form visualizarEncomendas
     */
    public visualizarEncomendas() {
        initComponents();
        arrumaTabela();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        CT_user = new javax.swing.JTextField();
        B_filtrar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tab_encomendas = new javax.swing.JTable();
        B_novo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Localizar venda");

        jLabel2.setText("Digite um cliente:");

        B_filtrar.setText("Filtrar");
        B_filtrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_filtrarActionPerformed(evt);
            }
        });

        Tab_encomendas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nome", "Telefone", "Data de Entrega", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Tab_encomendas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Tab_encomendasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Tab_encomendas);

        B_novo.setText("Novo");
        B_novo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_novoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 756, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CT_user, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(B_filtrar)
                        .addGap(35, 35, 35)
                        .addComponent(B_novo)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(CT_user, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(B_filtrar)
                    .addComponent(B_novo))
                .addGap(34, 34, 34)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void B_filtrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_filtrarActionPerformed
        arrumaTabela();
    }//GEN-LAST:event_B_filtrarActionPerformed

    private void Tab_encomendasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Tab_encomendasMouseClicked
        int res = Tab_encomendas.getSelectedRow();
        pedido = (encomenda) listaEncomendas.get(res);
        constroiEncomenda();
        vendaEncomenda ve = new vendaEncomenda();
        fechar = true;
        ve.armazenarDados(pedido);
        ve.arrumaTelaUpdate(pedido);
        ve.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Tab_encomendasMouseClicked

    private void B_novoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_novoActionPerformed
        if (!fechar) {
            vendaEncomenda ve = new vendaEncomenda();
            ve.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_B_novoActionPerformed

    public void arrumaTabela() {
        encomendaControl enco = new encomendaControl();
        listaEncomendas = enco.pesquisarEncomendas(CT_user.getText());
        DefaultTableModel modelo = (DefaultTableModel) Tab_encomendas.getModel();
        while (modelo.getRowCount() != 0) {
            modelo.removeRow(0);
        }
        for (int i = 0; i < listaEncomendas.size(); i++) {
            encomenda dado = (encomenda) listaEncomendas.get(i);
            String[] linha = new String[4];
            linha[0] = dado.client.getNome();
            linha[1] = String.valueOf(dado.client.getTelefone());
            linha[2] = formataData(dado.getDiaEntrega());
            linha[3] = String.valueOf(dado.isStatus());
            modelo.addRow(linha);
        }
        Tab_encomendas.setModel(modelo);
    }

    public String formataData(String data) {
        String dataFormatada = data.substring(8, 10) + "/" + data.substring(5, 7) + "/" + data.substring(0, 4);
        return dataFormatada;
    }
    
    public void constroiEncomenda(){
        produtoEncomendaControl localizarItens= new produtoEncomendaControl();
        pedido.adicionarItens(localizarItens.localizarProdutos(pedido.getCodigoEncomenda()));
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(visualizarEncomendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(visualizarEncomendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(visualizarEncomendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(visualizarEncomendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new visualizarEncomendas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton B_filtrar;
    private javax.swing.JButton B_novo;
    private javax.swing.JTextField CT_user;
    private javax.swing.JTable Tab_encomendas;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
